### ISSUE TITLE
3.6.0 - Database connection [redirect] not configured

### ISSUE THREAD

**Issue by atomicjam** [riasvdv/statamic-redirect#168]
We have been using Redirect for over a year successfully but updated to 3.6.0 yesterday and now have server 500 error on any redirects and on the redirect console in statamic.

Everything else is working correctly on the site. 

```
Environment
Laravel Version: 10.42.0
PHP Version: 8.3.2-1+ubuntu22.04.1+deb.sury.org+1
Composer Version: 2.3.10
Environment: production
Debug Mode: OFF
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 4
Antlers: runtime
Stache Watcher: Disabled
Static Caching: half
Version: 4.45.0 PRO

Statamic Addons
mitydigital/feedamic: 2.3.0
mitydigital/sitemapamic: 2.3.9
rias/statamic-redirect: 3.6.0
teamnovu/statamic-images-missing-alt: 1.0.2
```

sqlite3 is install as per the reqs

redirect config file is default but included 
```

<?php

return [
    /**
     * Whether Redirect should be enabled
     */
    'enable' => env('REDIRECT_ENABLED', true),

    /**
     * Controls whether Redirect automatically creates a redirect
     * when an entry's URI changes.
     */
    'create_entry_redirects' => env('REDIRECT_AUTO_CREATE', true),

    /**
     * Controls whether Redirect logs 404 errors
     */
    'log_errors' => env('REDIRECT_LOG_ERRORS', true),

    /**
     * Controls whether Redirect logs individual hits
     */
    'log_hits' => env('REDIRECT_LOG_HITS', true),

    /**
     * Should error logs be cleaned? Make sure your schedule is running.
     */
    'clean_errors' => env('REDIRECT_CLEAN_ERRORS', true),

    /**
     * Should error logs be cleaned when saving a new error?
     */
    'clean_errors_on_save' => env('REDIRECT_CLEAN_ON_SAVE', true),

    /**
     * Error logs older than this will be deleted.
     * @link http://php.net/manual/en/dateinterval.createfromdatestring.php
     */
    'clean_older_than' => '1 month',

    /*
     * The maximum number of unique errors to keep.
     * This does not include individual hits.
     */
    'keep_unique_errors' => 1000,

    /*
     * The database connection redirect should use to store errors
     * by default this is the included 'redirect' connection
     * that uses an sqlite database in storage.
     */
    'connection' => 'redirect',

    /*
     * Customize where on filesystem the redirects are being stored
     * Useful when using a non-conventional setup where data should
     * not be inside the usual content/redirects folder
     */
    'redirect_store' => base_path('content/redirects'),

```

error thrown in laravel logs 

```
[2024-01-25 09:40:07] production.ERROR: Database connection [redirect] not configured. {"exception":"[object] (InvalidArgumentException(code: 0): Database connection [redirect] not configured. at /data/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:196)
[stacktrace]
#0 /data/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(159): Illuminate\\Database\\DatabaseManager->configuration()
#1 /data/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(101): Illuminate\\Database\\DatabaseManager->makeConnection()
#2 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1819): Illuminate\\Database\\DatabaseManager->connection()
#3 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1785): Illuminate\\Database\\Eloquent\\Model::resolveConnection()
#4 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1576): Illuminate\\Database\\Eloquent\\Model->getConnection()
#5 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1495): Illuminate\\Database\\Eloquent\\Model->newBaseQueryBuilder()
#6 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1531): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#7 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1484): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#8 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2334): Illuminate\\Database\\Eloquent\\Model->newQuery()
#9 /data/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\\Database\\Eloquent\\Model->__call()
#10 /data/www/vendor/rias/statamic-redirect/src/Data/Error.php(64): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#11 /data/www/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(95): Rias\\StatamicRedirect\\Data\\Error::findByUrl()
#12 /data/www/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(41): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->createError()
#13 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Rias\\StatamicRedirect\\Http\\Middleware\\HandleNotFound->handle()
#14 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#16 /data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#17 /data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#18 /data/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#19 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#20 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#21 /data/www/vendor/statamic/cms/src/Http/Middleware/StopImpersonating.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\StopImpersonating->handle()
#23 /data/www/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(17): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\DisableFloc->handle()
#25 /data/www/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#27 /data/www/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#29 /data/www/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#31 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#34 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#37 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#39 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#41 /data/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#43 /data/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#45 /data/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#47 /data/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#48 /data/www/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"} 


```

**Comment by atomicjam** [comment]
/content/redirects/default folder has about 50 yaml files in it 

e.g
```
-94a2-a60422ae027d.yaml
id: fed74c84-2adc-4f0c-94a2-a60422ae027d
enabled: true
source: /news/recent-news/
destination: /news
type: '301'
match_type: exact
```

**Comment by atomicjam** [comment]
/config/database.php has sqlite setup as follows

```
 'connections' => [

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],
```

and no settings for mysql since we use statamic flat file system and caching and do not run a database

**Comment by atomicjam** [comment]
rolling back in composer file to 3.5 and everything works again it appears to be a change specifically in 3.6
```
"rias/statamic-redirect": "3.5",
```

**Comment by riasvdv** [comment]
Sorry about that, this should be fixed in the latest release!
