### ISSUE TITLE
stache error with disabled logging

### ISSUE THREAD

**Issue by rrelmy** [riasvdv/statamic-redirect#31]
We see a lot of error like this on production with a site with disabled logging.

I think the might be caused by disabled logging and a old config which implies `log_hits: true` or just a missing check in the logic.

```
[2021-11-22 10:24:41] production.DEBUG: RuntimeException: SplFileInfo::getMTime(): stat failed for /srv/users/some-website/apps/some-website/storage/redirect/errors/8a/53/8a53792b-22ca-4c98-beca-7f00e0b67581.yaml in /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Traverser.php:38
Stack trace:
#0 /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Traverser.php(38): SplFileInfo->getMTime()
#1 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(711): Statamic\Stache\Traverser->Statamic\Stache\{closure}(Object(Symfony\Component\Finder\SplFileInfo), 50556)
#2 /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Traverser.php(39): Illuminate\Support\Collection->mapWithKeys(Object(Closure))
#3 /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Stores/Store.php(182): Statamic\Stache\Traverser->traverse(Object(Rias\StatamicRedirect\Stache\Errors\ErrorStore))
#4 /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Stores/Store.php(284): Statamic\Stache\Stores\Store->handleFileChanges()
#5 /srv/users/some-website/apps/some-website/vendor/rias/statamic-redirect/src/Stache/Errors/ErrorQueryBuilder.php(16): Statamic\Stache\Stores\Store->paths()
#6 /srv/users/some-website/apps/some-website/vendor/statamic/cms/src/Stache/Query/Builder.php(26): Rias\StatamicRedirect\Stache\Errors\ErrorQueryBuilder->getFilteredKeys()
#7 /srv/users/some-website/apps/some-website/vendor/rias/statamic-redirect/src/Stache/Errors/ErrorRepository.php(26): Statamic\Stache\Query\Builder->get()
#8 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Rias\StatamicRedirect\Stache\Errors\ErrorRepository->all()
#9 /srv/users/some-website/apps/some-website/vendor/rias/statamic-redirect/src/Jobs/CleanErrorsJob.php(26): Illuminate\Support\Facades\Facade::__callStatic('all', Array)
#10 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Rias\StatamicRedirect\Jobs\CleanErrorsJob->handle()
#11 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#12 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#13 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#16 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Rias\StatamicRedirect\Jobs\CleanErrorsJob))
#17 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Rias\StatamicRedirect\Jobs\CleanErrorsJob))
#18 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow(Object(Rias\StatamicRedirect\Jobs\CleanErrorsJob))
#20 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(193): Illuminate\Bus\Dispatcher->dispatch(Object(Rias\StatamicRedirect\Jobs\CleanErrorsJob))
#21 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(31): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#22 /srv/users/some-website/apps/some-website/vendor/rias/statamic-redirect/src/Http/Middleware/HandleNotFound.php(37): Rias\StatamicRedirect\Jobs\CleanErrorsJob::dispatchIf(true)
#23 /srv/users/some-website/apps/some-website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Rias\StatamicRedirect\Http\Middleware\HandleNotFound->handle(Object(Illuminate\Http\Request), Object(Closure))
```

The config is based on an older version of the addon I suppose as it is missing `log_hits`
``` php
<?php

return [

    /**
     * Controls whether Redirect automatically creates a redirect
     * when an entry's URI changes.
     */
    'create_entry_redirects' => true,

    /**
     * Controls whether Redirect logs 404 errors
     */
    'log_errors' => false,

    /**
     * Should error logs be cleaned? Make sure your schedule is running.
     */
    'clean_errors' => true,

    /**
     * Should error logs be cleaned when saving a new error?
     */
    'clean_errors_on_save' => true,

    /**
     * Error logs older than this will be deleted.
     * @link http://php.net/manual/en/dateinterval.createfromdatestring.php
     */
    'clean_older_than' => '1 month',

    /*
     * The maximum number of unique errors to keep.
     * This does not include individual hits.
     */
    'keep_unique_errors' => 1000,

    /*
     * Error repository, you can change this to use a different
     * storage method for the errors. The class must implement
     * \Rias\StatamicRedirect\Contracts\ErrorRepository
     */
    'error_repository' => \Rias\StatamicRedirect\Stache\Errors\ErrorRepository::class,

    /*
     * Redirect repository, you can change this to use a different
     * storage method for the redirect. The class must implement
     * \Rias\StatamicRedirect\Contracts\RedirectRepository
     */
    'redirect_repository' => \Rias\StatamicRedirect\Stache\Redirects\RedirectRepository::class,
];
```

**Comment by riasvdv** [comment]
The exception seems to relate to not being able to read the error file, try to clear your cache to see if that fixes it.

**Comment by rrelmy** [comment]
I think what fixed is disabling `clean_errors` so it did not try to clean the non-existing files.
