### ISSUE TITLE
ERROR: Route [statamic.cp.redirect.index] not defined.

### ISSUE THREAD

**Issue by Hesesses** [riasvdv/statamic-redirect#94]
Hello,

I updated statamic and the plugin to latest version and getting an error after logging in to statamic cp

```
ERROR: Route [statamic.cp.redirect.index] not defined. (View: /vendor/statamic/cms/resources/views/layout.blade.php) {"view":{"view":"/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php","data":[]},"userId":"43e0d910-4436-404a-aaf9-d9e1c09a64eb","exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Route [statamic.cp.redirect.index] not defined. (View: /vendor/statamic/cms/resources/views/layout.blade.php) at /vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:444)
[stacktrace]
#0 /vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(739): Illuminate\\Routing\\UrlGenerator->route()
#1 /vendor/statamic/cms/src/Statamic.php(169): route()
#2 /vendor/statamic/cms/src/helpers.php(9): Statamic\\Statamic::cpRoute()
#3 /vendor/rias/statamic-redirect/src/RedirectServiceProvider.php(113): cp_route()
#4 /vendor/statamic/cms/src/CP/Navigation/Nav.php(135): Rias\\StatamicRedirect\\RedirectServiceProvider->Rias\\StatamicRedirect\\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(245): Statamic\\CP\\Navigation\\Nav->Statamic\\CP\\Navigation\\{closure}()
#6 /vendor/statamic/cms/src/CP/Navigation/Nav.php(136): Illuminate\\Support\\Collection->each()
#7 /vendor/statamic/cms/src/CP/Navigation/Nav.php(105): Statamic\\CP\\Navigation\\Nav->buildExtensions()
#8 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Statamic\\CP\\Navigation\\Nav->build()
...
```

Any ideas?

**Comment by riasvdv** [comment]
Do you have route caching? Try running `php artisan route:clear` and see if it works
